version: '2'
services:
  db:
    image: kcollins/mssql:latest
    ports:
      - 1436:1433
    volumes:
      - db_data:/var/opt/mssql
      - ./db-backups:/backups
      - ./db-init:/docker-entrypoint-initdb.d
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: $TYPEORM_PASSWORD
      MSSQL_DATABASE: $TYPEORM_DATABASE
      MSSQL_USER: $TYPEORM_USERNAME
      MSSQL_PASSWORD: $TYPEORM_PASSWORD
      MSSQL_PID: Developer
volumes:
  db_data:
