export enum ENV_CONSTANTS {
  // DB
  TYPEORM_HOST = 'TYPEORM_HOST',
  TYPEORM_PORT = 'TYPEORM_PORT',
  TYPEORM_USERNAME = 'TYPEORM_USERNAME',
  TYPEORM_PASSWORD = 'TYPEORM_PASSWORD',
  TYPEORM_DATABASE = 'TYPEORM_DATABASE',
  TYPEORM_ENTITIES = 'TYPEORM_ENTITIES',
  TYPEORM_CONNECTION = 'TYPEORM_CONNECTION',
  TYPEORM_MIGRATIONS_DIR = 'TYPEORM_MIGRATIONS_DIR',
  TYPEORM_MIGRATIONS = 'TYPEORM_MIGRATIONS',
  TYPEORM_MIGRATIONS_RUN = 'TYPEORM_MIGRATIONS_RUN',
  TYPEORM_SYNCHRONIZE = 'TYPEORM_SYNCHRONIZE',
  TYPEORM_DEBUG = 'TYPEORM_DEBUG',
  // APP
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  WEB_APP_BASE_URL = 'WEB_APP_BASE_URL',
  //AUTH
  AUTH_JWT_SECRET = 'AUTH_JWT_SECRET',
  // AZURE_STORAGE
  AZURE_STORAGE_ACCESS_KEY = 'AZURE_STORAGE_ACCESS_KEY',
  AZURE_STORAGE_ACCOUNT = 'AZURE_STORAGE_ACCOUNT',
}
